[build-system]
requires = ["hatchling>=1.8.0"]
build-backend = "hatchling.build"

[project]
name = "netket_pro"
description="Internal extensions for NetKet of the Ecole Polytechnique and collaborators group."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "netket>=3.14",
    "numba>=0.59",
    "einops>=0.6",
    "orbax-checkpoint>=0.6.4",
    "sparse>=0.15",
]
#dynamic = ["version"]
version = "0.1"

[project.optional-dependencies]
dev = [
    "pytest>=6",
    "pytest-cov>=2.10.1",
    "pytest-json-report>=1.3",
    "pytest-datadir>=1.3",
    "coverage>=5",
    "pre-commit>=2.7",
    "black==24.2.0",
    "ruff==0.6.2",
    "wheel>=0.38",
    "build >= 1.2",
    "qutip>=5",
    "neural_tangents >= 0.6",
]
docs = [
    "Sphinx>=7.0,<7.4",
    "sphinx-design>=0.4.0",
    "sphinx-autodoc-typehints>=1.22,<3.0",
    "sphinxcontrib-fulltoc~=1.2.0",
    "sphinxcontrib-jsmath~=1.0.1",
    "myst-parser>=2.0.0,<3.1.0",
    "myst-nb>=1.0,<1.2",
    "sphinx-book-theme~=1.1.0",
    "sphinx-rtd-theme >= 3.0.0",
]
extras = [
    "neural_tangents",
]

[tool.hatch.build]
include = ["netket_pro*"]

[tool.uv.sources]
neural-tangents = {git = "https://github.com/google/neural-tangents"}


[tool.coverage.run]
branch = true
parallel = true
concurrency = ["multiprocessing"]
command_line = "-m pytest --verbose test"
source = ["netket_pro"]

[tool.pytest.ini_options]
addopts = "--color=yes --verbose --durations=100 --tb=short"
doctest_optionflags = "NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL NUMBER"
filterwarnings = [
    "ignore::UserWarning",
    "ignore:No GPU/TPU found, falling back to CPU.:UserWarning",
    "ignore:the imp module is deprecated in favour of importlib.*:DeprecationWarning",
    "ignore:`np.long`",
    "ignore:`np.int` is a deprecated alias for the builtin `int`",
    "ignore::DeprecationWarning:tensorboardX",
    "ignore::netket.errors.UnoptimalSRtWarning"
]
testpaths = [
    "test",
]

[tool.ruff]
target-version = "py39"
line-length = 88
exclude = ["netket_pro/_src/external", "deepnets"]

[tool.ruff.lint]
select = ["E", "F", "W", "D410", "UP",]
fixable = ["E", "F", "W", "D", "UP"]
ignore = ["E501", "E731", "E741", "D100", "D101", "D102", "D103", "D105", "D107", "D404", "D417"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402","F401"]
"netket/nn/activation.py" = ["F401"]
"examples/*" = ["F401", "E402"]
"docs/conf.py" = ["F401", "E402"]
"docs/sphinx_extensions/*" = ["F401", "E402", "UP"]

[tool.hatch.metadata]
allow-direct-references = true
