name: Checks

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    name: Formatting (black)

    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Pip install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -v black==23.10.1

      - name: Black Code Formatter
        run: black --check --diff --color .

  ruff:
    name: Code (ruff)

    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install pipx on self-hosted
        run: |
          sudo apt install -y pipx

      - name: Set up Python 3.11
        uses: chartboost/ruff-action@v1
        with:
          version: 0.1.4
          args: --config pyproject.toml
          src: netket_pro examples test
